modLoader="javafml"
loaderVersion = "[${forge_version},)"
license="${mod_license}"
issueTrackerURL="https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/terrafirmagreg-core"
logoFile= "icon.png"
authors="Exception, Xikaro"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "1.2.0.a"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "tfc"
mandatory = true
versionRange = "3.2.0"
ordering = "AFTER"
side = "BOTH"

#[[dependencies.${mod_id}]]
#modId = "ae2"
#mandatory = true
#versionRange = "[15.0.15,)"
#ordering = "NONE"
#side = "BOTH"

[[dependencies.${mod_id}]]
modId = "firmalife"
mandatory = true
versionRange = "2.1.0"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "firmaciv"
mandatory = true
versionRange = "[0.2.2-alpha,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "create"
mandatory = false
versionRange = "0.5.1.f"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "tfcambiental"
mandatory = true
versionRange = "3.2.0"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = true
versionRange = "2001.6.4-build.138+forge"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftbteams"
mandatory = true
versionRange = "[2001.1.4,)"
ordering = "NONE"
side = "BOTH"


