modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="terrafirmagreg"
version="0.0.1"
displayName="TerraFirmaGreg"
displayURL=""
#logoFile="examplemod.png"
credits="Dead"
authors="Exception"

description="Lol"


