modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/GreateBeyondTheHorizon/Greate/issues"

[[mods]]
modId="greate"
version="0.0.7"
displayName="Greate"
displayURL="https://modrinth.com/mod/greate"
#logoFile="examplemod.png"
credits="Both the Create & Gregtech devs for making awesome mods!"
authors="Electrolyte"

description="Create Gregified"


