modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "LGPLv3"
issueTrackerURL = "https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues"

# ============================================================
# TFG
# ============================================================

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
logoFile = "${mod_logo_path}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "gtceu"
mandatory = true
versionRange = "[1.6.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "tfc"
mandatory = true
versionRange = "[3.2.24,)"
ordering = "AFTER"
side = "BOTH"

# ============================================================
# TFG Ambiental
# ============================================================

[[mods]]
modId = "tfcambiental"
version = "${mod_version}"
displayName = "TFG Ambiental"
authors = "Lumintorious, ${mod_authors}"
description = '''A TerraFirmaGreg addon that implements a temperature system.'''

[[dependencies.tfcambiental]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfcambiental]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfcambiental]]
modId = "curios"
mandatory = true
versionRange = "[5.14.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tfcambiental]]
modId = "tfc"
mandatory = true
versionRange = "[3.2.24,)"
ordering = "AFTER"
side = "BOTH"

# ============================================================
# TFG Textile
# ============================================================

[[mods]]
modId = "tfc_textile"
version = "${mod_version}"
displayName = "TFG Textile"
authors = "Atoba Azul, ${mod_authors}"
description = '''A TerraFirmaGreg addon that implements clothes.'''

[[dependencies.tfc_textile]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfc_textile]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.tfc_textile]]
modId = "tfc"
mandatory = true
versionRange = "[3.2.24,)"
ordering = "AFTER"
side = "BOTH"
