modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="terrafirmagreg"
version="0.0.1"
displayName="TerraFirmaGreg"
displayURL=""
#logoFile="examplemod.png"
credits="Dead"
authors="Exception"

description="Lol"

[[dependencies.terrafirmagreg]]
modId = "gtceu"
mandatory = false
versionRange = "1.0.13"
ordering = "AFTER"
side = "BOTH"


