modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/terrafirmagreg-mod"
logoFile="terrafirmagreg.png"
authors="${mod_authors}"
description='''${mod_description}'''


[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[1.0.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "tfc"
mandatory = true
versionRange = "[3.1.4-beta,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
mandatory = true
versionRange = "[15.0.15,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftbteams"
mandatory = true
versionRange = "[2001.1.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
