modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/issues"

[[mods]]
modId="terrafirmagreg"
version="0.0.1"
displayName="TerraFirmaGreg"
credits="By Exception, Xikaro"
authors="Exception"
description="Compat mod for TFC and GTCEu"

[[dependencies.terrafirmagreg]]
modId = "gtceu"
mandatory = false
versionRange = "[1.0.13,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrafirmagreg]]
modId = "tfc"
mandatory = false
versionRange = "[0.0.0-indev,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terrafirmagreg]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.terrafirmagreg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"


