modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/issues"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
credits="By Exception, Xikaro"
authors="Exception"
description = "${mod_description}"
logoFile = "logo.png"
displayURL = "${mod_url}"

[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = true
versionRange = "[1.0.15,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "tfc"
mandatory = true
versionRange = "[3.0.3-beta,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
mandatory = true
versionRange = "[15.0.15,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47.1.3,47.1.6),[47.2.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "AFTER"
side = "BOTH"


