package su.terrafirmagreg.core.compat.emi;

public record ExportedOreVeinInfo(String ID, String dimension, int rarity, double density, int minY, int maxY, int size, int height, int radius, String[] types, WeightedBlock[] blocks) {
    public record WeightedBlock(String ore, int weight, double weightPercent) {}

    // This data is automatically generated by the OresToFieldGuide program in Tools-Modern.

    public static final ExportedOreVeinInfo[] ORE_VEIN_INFO = {
            new ExportedOreVeinInfo("deep_garnet_amethyst", "earth",
                    230, 0.25, -64, 26, 40, 8, 0, new String[] {
                    "quartzite", "slate", "phyllite", "schist", "gneiss", "marble", "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_red_garnet_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_yellow_garnet_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_amethyst_ore", 65, 65),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_opal_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("deep_garnet_opal", "earth",
                    220, 0.35, -64, 62, 26, 6, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_red_garnet_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_yellow_garnet_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_amethyst_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_opal_ore", 55, 55)
            }),
            new ExportedOreVeinInfo("deep_gold", "earth",
                    260, 0.45, -64, 30, 32, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_goethite_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_yellow_limonite_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_hematite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_gold_ore", 75, 75)
            }),
            new ExportedOreVeinInfo("deep_hematite", "earth",
                    220, 0.35, -64, 30, 30, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_goethite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_yellow_limonite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_hematite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_gold_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_ruby_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("deep_limonite", "earth",
                    240, 0.35, -64, 30, 32, 0, 0, new String[] {
                    "marble", "limestone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:marble_goethite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:marble_yellow_limonite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:marble_hematite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:marble_malachite_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("deep_magnetite", "earth",
                    225, 0.3, -64, 30, 20, 0, 0, new String[] {
                    "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_magnetite_ore", 5, 8),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_vanadium_magnetite_ore", 15, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_chromite_ore", 20, 33),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_gold_ore", 15, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_sapphire_ore", 5, 8)
            }),
            new ExportedOreVeinInfo("deep_molybdenum", "earth",
                    245, 0.45, -64, 10, 26, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_wulfenite_ore", 40, 47),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_molybdenite_ore", 30, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_powellite_ore", 15, 17)
            }),
            new ExportedOreVeinInfo("deep_pitchblende", "earth",
                    220, 0.45, -64, -20, 24, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_pitchblende_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_uraninite_ore", 50, 50)
            }),
            new ExportedOreVeinInfo("deep_sapphire", "earth",
                    180, 0.35, -64, 26, 28, 8, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_almandine_ore", 35, 38),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_pyrope_ore", 25, 27),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_sapphire_ore", 15, 16),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_green_sapphire_ore", 15, 16)
            }),
            new ExportedOreVeinInfo("deep_scheelite", "earth",
                    240, 0.35, -64, 0, 20, 0, 0, new String[] {
                    "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_scheelite_ore", 45, 45),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_tungstate_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_lithium_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("deep_sheldonite", "earth",
                    320, 0.3, -64, 0, 30, 0, 0, new String[] {
                    "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_bornite_ore", 35, 53),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_cooperite_ore", 25, 38),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_platinum_ore", 5, 7)
            }),
            new ExportedOreVeinInfo("deep_topaz", "earth",
                    260, 0.3, -64, 26, 28, 7, 0, new String[] {
                    "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_blue_topaz_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_topaz_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_chalcocite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_bornite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_apatite", "earth",
                    220, 0.25, -32, 60, 34, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_apatite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_tricalcium_phosphate_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_pyrochlore_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_basaltic_sands", "earth",
                    160, 0.3, -32, 60, 48, 9, 0, new String[] {
                    "granite", "basalt"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_basaltic_mineral_sand_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_granitic_mineral_sand_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_fullers_earth_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_gypsum_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_beryllium", "earth",
                    250, 0.35, -32, 50, 0, 60, 10, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_beryllium_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_emerald_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_thorium_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_bismuthinite", "earth",
                    170, 0.4, -32, 75, 40, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_bismuth_ore", 80, 80),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_sulfur_ore", 9, 9),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_lead_ore", 11, 11)
            }),
            new ExportedOreVeinInfo("normal_cassiterite", "earth",
                    170, 0.4, -32, 75, 40, 0, 0, new String[] {
                    "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_cassiterite_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_tin_ore", 60, 60)
            }),
            new ExportedOreVeinInfo("normal_coal", "earth",
                    215, 0.55, 0, 210, 60, 0, 0, new String[] {
                    "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_coal_ore", 100, 100)
            }),
            new ExportedOreVeinInfo("normal_copper", "earth",
                    170, 0.4, -32, 75, 40, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_chalcopyrite_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_hematite_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_pyrite_ore", 10, 10),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_copper_ore", 65, 65)
            }),
            new ExportedOreVeinInfo("normal_garnet_tin", "earth",
                    270, 0.25, -40, 64, 40, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "granite", "diorite", "gabbro", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble", "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_cassiterite_sand_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_garnet_sand_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_asbestos_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_diatomite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_garnierite", "earth",
                    160, 0.4, -32, 60, 40, 0, 0, new String[] {
                    "gabbro", "diorite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_garnierite_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_nickel_ore", 10, 10),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_cobaltite_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_pentlandite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_cobalt_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_gold", "earth",
                    170, 0.4, -32, 60, 40, 12, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_goethite_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_yellow_limonite_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_hematite_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_gold_ore", 55, 55)
            }),
            new ExportedOreVeinInfo("normal_graphite", "earth",
                    80, 0.4, -64, -16, 16, 6, 0, new String[] {
                    "gabbro", "granite", "diorite", "schist", "gneiss", "quartzite", "phyllite", "slate", "marble", "dacite", "rhyolite", "andesite", "basalt", "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_graphite_ore", 45, 45),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_diamond_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_coal_ore", 30, 30)
            }),
            new ExportedOreVeinInfo("normal_hematite", "earth",
                    210, 0.4, -32, 75, 40, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_goethite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_yellow_limonite_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_hematite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_gold_ore", 5, 5)
            }),
            new ExportedOreVeinInfo("normal_lapis", "earth",
                    170, 0.25, -60, 10, 50, 0, 0, new String[] {
                    "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_lazurite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_sodalite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_lapis_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_calcite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_limonite", "earth",
                    190, 0.4, -32, 75, 40, 0, 0, new String[] {
                    "marble", "limestone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:marble_goethite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:marble_yellow_limonite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:marble_hematite_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:marble_malachite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_lubricant", "earth",
                    190, 0.25, -40, 56, 36, 0, 0, new String[] {
                    "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_soapstone_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_talc_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_glauconite_sand_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_pentlandite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_trona_ore", 10, 10)
            }),
            new ExportedOreVeinInfo("normal_magnetite", "earth",
                    200, 0.3, -32, 75, 30, 0, 0, new String[] {
                    "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_magnetite_ore", 70, 63),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_vanadium_magnetite_ore", 25, 22),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_gold_ore", 10, 9),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_chromite_ore", 5, 4)
            }),
            new ExportedOreVeinInfo("normal_manganese", "earth",
                    195, 0.3, -32, 60, 30, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_grossular_ore", 30, 37),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_spessartine_ore", 20, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_pyrolusite_ore", 20, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_tantalite_ore", 10, 12)
            }),
            new ExportedOreVeinInfo("normal_mica", "earth",
                    190, 0.25, 0, 210, 36, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_kyanite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_mica_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_bauxite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_pollucite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_monazite", "earth",
                    205, 0.25, -32, 50, 35, 0, 0, new String[] {
                    "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_bastnasite_ore", 50, 62),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_monazite_ore", 25, 31),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_neodymium_ore", 5, 6)
            }),
            new ExportedOreVeinInfo("normal_oilsands", "earth",
                    185, 0.2, 0, 70, 55, 0, 0, new String[] {
                    "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_oilsands_ore", 100, 100)
            }),
            new ExportedOreVeinInfo("normal_olivine", "earth",
                    180, 0.25, -40, 30, 26, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_bentonite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_magnesite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_olivine_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_glauconite_sand_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_quartz", "earth",
                    190, 0.3, -32, 100, 40, 0, 0, new String[] {
                    "shale", "quartzite", "schist", "gneiss"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_quartzite_ore", 35, 43),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_barite_ore", 30, 37),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_asbestos_ore", 15, 18)
            }),
            new ExportedOreVeinInfo("normal_redstone", "earth",
                    160, 0.4, -32, 100, 40, 0, 0, new String[] {
                    "granite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_redstone_ore", 45, 45),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_ruby_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_cinnabar_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("normal_salt", "earth",
                    175, 0.4, 30, 70, 40, 4, 0, new String[] {
                    "shale", "claystone", "limestone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_rock_salt_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_salt_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_lepidolite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:shale_borax_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_saltpeter", "earth",
                    210, 0.3, -32, 60, 40, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_saltpeter_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_diatomite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_electrotine_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_alunite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_silver", "earth",
                    160, 0.4, -32, 75, 40, 0, 0, new String[] {
                    "granite", "gneiss"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_galena_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_silver_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_lead_ore", 55, 55)
            }),
            new ExportedOreVeinInfo("normal_sphalerite", "earth",
                    170, 0.4, -32, 75, 40, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_sulfur_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_sphalerite_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_pyrite_ore", 25, 25)
            }),
            new ExportedOreVeinInfo("normal_spodumene", "earth",
                    180, 0.375, 20, 60, 35, 6, 0, new String[] {
                    "granite", "diorite", "gabbro", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_rock_salt_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_salt_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_lepidolite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_spodumene_ore", 35, 35)
            }),
            new ExportedOreVeinInfo("normal_sulfur", "earth",
                    165, 0.2, 0, 210, 45, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_sulfur_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_pyrite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_sphalerite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("normal_tetrahedrite", "earth",
                    170, 0.4, -32, 75, 40, 0, 0, new String[] {
                    "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_tetrahedrite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_copper_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_stibnite_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("surface_bismuthinite", "earth",
                    140, 0.25, 60, 210, 50, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "shale", "claystone", "limestone", "conglomerate", "dolomite", "chert", "chalk"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_bismuth_ore", 90, 90),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_sulfur_ore", 3, 3),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_lead_ore", 7, 7)
            }),
            new ExportedOreVeinInfo("surface_cassiterite", "earth",
                    135, 0.25, 60, 210, 50, 0, 0, new String[] {
                    "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_cassiterite_ore", 60, 60),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_tin_ore", 40, 40)
            }),
            new ExportedOreVeinInfo("surface_copper", "earth",
                    200, 0.25, 20, 217, 50, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_chalcopyrite_ore", 55, 61),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_zeolite_ore", 15, 16),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_cassiterite_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_realgar_ore", 15, 16)
            }),
            new ExportedOreVeinInfo("surface_sphalerite", "earth",
                    145, 0.25, 60, 210, 50, 0, 0, new String[] {
                    "rhyolite", "basalt", "andesite", "dacite", "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_sulfur_ore", 55, 55),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_sphalerite_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_pyrite_ore", 5, 5)
            }),
            new ExportedOreVeinInfo("surface_tetrahedrite", "earth",
                    140, 0.25, 60, 210, 50, 0, 0, new String[] {
                    "quartzite", "slate", "phyllite", "schist", "gneiss", "marble"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_tetrahedrite_ore", 60, 60),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_copper_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:quartzite_stibnite_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("moon_apatite", "moon",
                    250, 0.3, 0, 100, 35, 0, 0, new String[] {
                    "diorite", "moon_stone", "moon_deepslate"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_apatite_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_tricalcium_phosphate_ore", 35, 33),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_pyrochlore_ore", 40, 38),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_olivine_ore", 5, 4)
            }),
            new ExportedOreVeinInfo("moon_bauxite", "moon",
                    200, 0.4, 0, 80, 50, 0, 0, new String[] {
                    "basalt", "moon_stone", "moon_deepslate", "glacio_stone", "diorite", "rhyolite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_bauxite_ore", 35, 36),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_ilmenite_ore", 40, 42),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_armalcolite_ore", 20, 21)
            }),
            new ExportedOreVeinInfo("moon_beryllium", "moon",
                    260, 0.45, 0, 120, 0, 70, 10, new String[] {
                    "basalt", "moon_stone", "glacio_stone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_beryllium_ore", 35, 31),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_emerald_ore", 50, 45),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_thorium_ore", 1, 0),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_olivine_ore", 5, 4),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_rock_salt_ore", 20, 18)
            }),
            new ExportedOreVeinInfo("moon_desh", "moon",
                    230, 0.35, 10, 80, 45, 0, 0, new String[] {
                    "andesite", "dacite", "gabbro", "basalt"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_desh_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_ilmenite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_aluminium_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_armalcolite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("moon_garnierite", "moon",
                    250, 0.4, 5, 85, 55, 0, 0, new String[] {
                    "gabbro", "diorite", "rhyolite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_garnierite_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_nickel_ore", 20, 19),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_cobaltite_ore", 20, 19),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_pentlandite_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_cobalt_ore", 15, 14)
            }),
            new ExportedOreVeinInfo("moon_graphite", "moon",
                    260, 0.55, 0, 120, 0, 60, 12, new String[] {
                    "basalt", "moon_stone", "glacio_stone", "gabbro", "basalt"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_graphite_ore", 50, 52),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_diamond_ore", 35, 36),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_olivine_ore", 10, 10)
            }),
            new ExportedOreVeinInfo("moon_lubricant", "moon",
                    190, 0.25, 0, 66, 36, 0, 0, new String[] {
                    "diorite", "gabbro", "moon_stone", "moon_deepslate", "basalt"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_soapstone_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_talc_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_glauconite_sand_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_pentlandite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_trona_ore", 10, 10)
            }),
            new ExportedOreVeinInfo("moon_magnetite", "moon",
                    280, 0.3, 0, 90, 70, 0, 0, new String[] {
                    "diorite", "gabbro", "moon_stone", "moon_deepslate"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_magnetite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_vanadium_magnetite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_chromite_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_gold_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_sapphire_ore", 5, 5)
            }),
            new ExportedOreVeinInfo("moon_manganese", "moon",
                    215, 0.5, 5, 80, 40, 0, 0, new String[] {
                    "andesite", "basalt", "gabbro", "dacite", "basalt", "moon_deepslate"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_grossular_ore", 30, 37),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_spessartine_ore", 20, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_pyrolusite_ore", 20, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_tantalite_ore", 10, 12)
            }),
            new ExportedOreVeinInfo("moon_mica", "moon",
                    250, 0.25, 0, 120, 35, 0, 0, new String[] {
                    "diorite", "gabbro", "moon_stone", "moon_deepslate"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_kyanite_ore", 35, 33),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_mica_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_bauxite_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_pollucite_ore", 15, 14),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_olivine_ore", 5, 4)
            }),
            new ExportedOreVeinInfo("moon_molybdenum", "moon",
                    245, 0.45, 0, 50, 40, 0, 0, new String[] {
                    "basalt", "dacite", "gabbro", "moon_deepslate"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_wulfenite_ore", 40, 44),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_molybdenite_ore", 30, 33),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_powellite_ore", 15, 16),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_olivine_ore", 5, 5)
            }),
            new ExportedOreVeinInfo("moon_monazite", "moon",
                    310, 0.2, 0, 70, 50, 0, 0, new String[] {
                    "glacio_stone", "andesite", "dacite", "rhyolite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:glacio_stone_bastnasite_ore", 50, 61),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:glacio_stone_monazite_ore", 25, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:glacio_stone_neodymium_ore", 5, 6),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:glacio_stone_olivine_ore", 1, 1)
            }),
            new ExportedOreVeinInfo("moon_pyrolusite", "moon",
                    210, 0.25, 20, 80, 40, 0, 0, new String[] {
                    "andesite", "basalt", "gabbro", "moon_stone", "moon_deepslate"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_pyrolusite_ore", 40, 38),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_cobaltite_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_cobalt_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:andesite_tantalite_ore", 15, 14)
            }),
            new ExportedOreVeinInfo("moon_quartz", "moon",
                    230, 0.3, 10, 100, 60, 0, 0, new String[] {
                    "basalt", "moon_deepslate", "gabbro", "moon_stone", "diorite", "glacio_stone", "dacite", "rhyolite", "andesite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_quartzite_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_certus_quartz_ore", 45, 45),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_nether_quartz_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_barite_ore", 5, 5)
            }),
            new ExportedOreVeinInfo("moon_redstone", "moon",
                    250, 0.2, 20, 100, 45, 0, 0, new String[] {
                    "dacite", "glacio_stone", "andesite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:dacite_redstone_ore", 45, 42),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:dacite_ruby_ore", 35, 33),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:dacite_cinnabar_ore", 20, 19),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:dacite_olivine_ore", 5, 4)
            }),
            new ExportedOreVeinInfo("moon_saltpeter", "moon",
                    210, 0.3, 0, 90, 35, 0, 0, new String[] {
                    "rhyolite", "andesite", "moon_deepslate", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_saltpeter_ore", 35, 29),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_soapstone_ore", 25, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_electrotine_ore", 45, 37),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_talc_ore", 15, 12)
            }),
            new ExportedOreVeinInfo("moon_sapphire", "moon",
                    280, 0.35, 0, 100, 28, 8, 0, new String[] {
                    "basalt", "moon_deepslate"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_almandine_ore", 35, 38),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_pyrope_ore", 25, 27),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_sapphire_ore", 15, 16),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_green_sapphire_ore", 15, 16),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_olivine_ore", 2, 2)
            }),
            new ExportedOreVeinInfo("moon_scheelite", "moon",
                    200, 0.45, 0, 70, 20, 0, 0, new String[] {
                    "rhyolite", "glacio_stone", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_scheelite_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_tungstate_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:rhyolite_lithium_ore", 10, 10)
            }),
            new ExportedOreVeinInfo("moon_sheldonite", "moon",
                    260, 0.3, 0, 70, 30, 0, 0, new String[] {
                    "basalt", "andesite", "glacio_stone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_bornite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_cooperite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_platinum_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_nickel_ore", 25, 25)
            }),
            new ExportedOreVeinInfo("moon_silver", "moon",
                    210, 0.4, 20, 75, 30, 0, 0, new String[] {
                    "moon_stone", "moon_deepslate", "rhyolite", "diorite", "dacite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:moon_stone_galena_ore", 30, 28),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:moon_stone_silver_ore", 45, 42),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:moon_stone_lead_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:moon_stone_olivine_ore", 5, 4)
            }),
            new ExportedOreVeinInfo("moon_sphalerite", "moon",
                    205, 0.4, 2, 75, 40, 0, 0, new String[] {
                    "basalt", "andesite", "gabbro", "dacite", "glacio_stone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_desh_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_sphalerite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_pyrite_ore", 35, 35)
            }),
            new ExportedOreVeinInfo("moon_topaz", "moon",
                    210, 0.5, 0, 120, 64, 25, 0, new String[] {
                    "basalt", "moon_deepslate", "gabbro", "moon_stone", "diorite", "glacio_stone", "dacite", "rhyolite", "andesite"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_blue_topaz_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_topaz_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_chalcocite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:basalt_bornite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_anthracite", "nether",
                    35, 0.8, 48, 127, 13, 4, 0, new String[] {
                    "deepslate"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("beneath:ore/nether_cursecoal", 100, 100)
            }),
            new ExportedOreVeinInfo("nether_apatite", "nether",
                    220, 0.35, 48, 128, 39, 0, 0, new String[] {
                    "schist", "gneiss"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:schist_apatite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:schist_tricalcium_phosphate_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:schist_pyrochlore_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_basaltic_sands", "nether",
                    160, 0.4, 48, 128, 48, 9, 0, new String[] {
                    "granite", "basalt"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_basaltic_mineral_sand_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_granitic_mineral_sand_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_fullers_earth_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_gypsum_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_beryllium", "nether",
                    250, 0.45, 32, 128, 0, 60, 12, new String[] {
                    "deepslate", "blackstone", "basalt", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_beryllium_ore", 35, 33),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_emerald_ore", 50, 47),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_thorium_ore", 1, 0),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_rock_salt_ore", 20, 18)
            }),
            new ExportedOreVeinInfo("nether_cassiterite", "nether",
                    170, 0.5, 32, 128, 45, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "gneiss", "schist", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_cassiterite_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_tin_ore", 60, 60)
            }),
            new ExportedOreVeinInfo("nether_copper", "nether",
                    170, 0.5, 32, 128, 45, 0, 0, new String[] {
                    "deepslate", "blackstone", "basalt", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_chalcopyrite_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_hematite_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_pyrite_ore", 10, 10),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_copper_ore", 65, 65)
            }),
            new ExportedOreVeinInfo("nether_garnet", "nether",
                    230, 0.35, 0, 128, 45, 8, 0, new String[] {
                    "deepslate", "blackstone", "basalt", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_red_garnet_ore", 10, 9),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_yellow_garnet_ore", 15, 14),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_amethyst_ore", 40, 38),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_opal_ore", 40, 38)
            }),
            new ExportedOreVeinInfo("nether_garnet_tin", "nether",
                    270, 0.35, 24, 128, 45, 0, 0, new String[] {
                    "deepslate", "blackstone", "dripstone", "granite", "diorite", "gabbro", "schist", "gneiss"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_cassiterite_sand_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_garnet_sand_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_asbestos_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_diatomite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_garnierite", "nether",
                    160, 0.5, 16, 128, 45, 0, 0, new String[] {
                    "gabbro", "diorite", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_garnierite_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_nickel_ore", 20, 19),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_cobaltite_ore", 20, 19),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_pentlandite_ore", 25, 23),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_cobalt_ore", 15, 14)
            }),
            new ExportedOreVeinInfo("nether_goethite", "nether",
                    240, 0.45, 0, 128, 37, 0, 0, new String[] {
                    "deepslate", "blackstone", "basalt", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_goethite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_yellow_limonite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_hematite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_malachite_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("nether_gold", "nether",
                    260, 0.55, 0, 128, 37, 0, 0, new String[] {
                    "gabbro", "diorite", "gneiss", "granite", "schist", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_goethite_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_yellow_limonite_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_hematite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_gold_ore", 75, 75)
            }),
            new ExportedOreVeinInfo("nether_graphite", "nether",
                    120, 0.35, 0, 128, 0, 60, 12, new String[] {
                    "gabbro", "gneiss", "diorite", "schist", "granite", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_graphite_ore", 45, 45),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_diamond_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_coal_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_hematite", "nether",
                    220, 0.45, 0, 128, 35, 0, 0, new String[] {
                    "deepslate", "blackstone", "basalt", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_goethite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_yellow_limonite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_hematite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_gold_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_ruby_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("nether_lapis", "nether",
                    220, 0.35, 32, 128, 40, 0, 0, new String[] {
                    "deepslate", "dripstone", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_lazurite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_sodalite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_lapis_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_calcite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_lubricant", "nether",
                    250, 0.35, 32, 128, 41, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "schist", "gneiss", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_soapstone_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_talc_ore", 20, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_glauconite_sand_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_pentlandite_ore", 15, 15),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_trona_ore", 10, 10)
            }),
            new ExportedOreVeinInfo("nether_magnetite", "nether",
                    205, 0.4, 0, 128, 39, 0, 0, new String[] {
                    "deepslate", "blackstone", "basalt", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_magnetite_ore", 10, 20),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_vanadium_magnetite_ore", 15, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_chromite_ore", 5, 10),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_gold_ore", 15, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_sapphire_ore", 5, 10)
            }),
            new ExportedOreVeinInfo("nether_manganese", "nether",
                    225, 0.4, 32, 128, 45, 0, 0, new String[] {
                    "deepslate", "basalt", "blackstone", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_grossular_ore", 30, 37),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_spessartine_ore", 20, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_pyrolusite_ore", 20, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_tantalite_ore", 10, 12)
            }),
            new ExportedOreVeinInfo("nether_mica", "nether",
                    220, 0.35, 32, 128, 41, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "schist", "gneiss", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_kyanite_ore", 35, 46),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_mica_ore", 25, 33),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_pollucite_ore", 15, 20)
            }),
            new ExportedOreVeinInfo("nether_molybdenum", "nether",
                    245, 0.55, 0, 128, 31, 0, 0, new String[] {
                    "gneiss", "schist", "granite", "diorite", "gabbro", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gneiss_wulfenite_ore", 40, 42),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gneiss_molybdenite_ore", 30, 31),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gneiss_powellite_ore", 10, 10),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gneiss_nickel_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_monazite", "nether",
                    245, 0.35, 24, 128, 45, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "schist", "gneiss", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_bastnasite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_monazite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_neodymium_ore", 25, 25)
            }),
            new ExportedOreVeinInfo("nether_naquadah", "nether",
                    250, 0.3, 0, 38, 32, 0, 0, new String[] {
                    "blackstone", "basalt"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:blackstone_naquadah_ore", 75, 75),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:blackstone_plutonium_ore", 25, 25)
            }),
            new ExportedOreVeinInfo("nether_olivine", "nether",
                    250, 0.35, 24, 128, 31, 0, 0, new String[] {
                    "deepslate", "basalt", "blackstone", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_bentonite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_magnesite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_olivine_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_glauconite_sand_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_pitchblende", "nether",
                    220, 0.55, 0, 128, 29, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "schist", "gneiss", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_pitchblende_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_uraninite_ore", 50, 50)
            }),
            new ExportedOreVeinInfo("nether_quartz", "nether",
                    150, 0.4, 0, 128, 45, 0, 0, new String[] {
                    "deepslate", "blackstone", "basalt", "dripstone", "granite", "diorite", "gabbro"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_quartzite_ore", 30, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_nether_quartz_ore", 65, 54),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_barite_ore", 25, 20)
            }),
            new ExportedOreVeinInfo("nether_redstone", "nether",
                    160, 0.5, 0, 128, 45, 0, 0, new String[] {
                    "granite", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_redstone_ore", 45, 45),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_ruby_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_cinnabar_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("nether_saltpeter", "nether",
                    210, 0.4, 32, 128, 50, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "schist", "gneiss", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_saltpeter_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_diatomite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_electrotine_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_alunite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_sapphire", "nether",
                    180, 0.45, 0, 128, 33, 8, 0, new String[] {
                    "gabbro", "granite", "gneiss", "diorite", "schist", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_almandine_ore", 35, 38),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_pyrope_ore", 25, 27),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_sapphire_ore", 15, 16),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:gabbro_green_sapphire_ore", 15, 16)
            }),
            new ExportedOreVeinInfo("nether_scheelite", "nether",
                    180, 0.45, 0, 128, 25, 0, 0, new String[] {
                    "granite", "diorite", "gabbro", "gneiss", "schist", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_scheelite_ore", 45, 45),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_tungstate_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_lithium_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("nether_sheldonite", "nether",
                    250, 0.4, 0, 128, 35, 0, 0, new String[] {
                    "deepslate", "blackstone", "basalt", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_bornite_ore", 35, 41),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_cooperite_ore", 25, 29),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_platinum_ore", 5, 5),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_nickel_ore", 20, 23)
            }),
            new ExportedOreVeinInfo("nether_silver", "nether",
                    160, 0.5, 24, 128, 45, 0, 0, new String[] {
                    "granite", "gneiss", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_galena_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_silver_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:granite_lead_ore", 35, 35)
            }),
            new ExportedOreVeinInfo("nether_sphalerite", "nether",
                    170, 0.5, 32, 128, 45, 0, 0, new String[] {
                    "deepslate", "basalt", "blackstone", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_sulfur_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_sphalerite_ore", 40, 40),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_pyrite_ore", 25, 25)
            }),
            new ExportedOreVeinInfo("nether_sulfur", "nether",
                    165, 0.3, 0, 128, 50, 0, 0, new String[] {
                    "diorite", "basalt", "blackstone", "schist"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_sulfur_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_pyrite_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:diorite_sphalerite_ore", 15, 15)
            }),
            new ExportedOreVeinInfo("nether_sylvite", "nether",
                    75, 0.6, 0, 64, 17, 0, 0, new String[] {
                    "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("beneath:ore/blackstone_sylvite", 100, 100)
            }),
            new ExportedOreVeinInfo("nether_tetrahedrite", "nether",
                    170, 0.5, 32, 128, 45, 0, 0, new String[] {
                    "deepslate", "dripstone", "schist", "gneiss", "blackstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_tetrahedrite_ore", 50, 50),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_copper_ore", 30, 30),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:deepslate_stibnite_ore", 20, 20)
            }),
            new ExportedOreVeinInfo("nether_topaz", "nether",
                    180, 0.4, 0, 128, 33, 7, 0, new String[] {
                    "blackstone", "deepslate", "basalt", "dripstone"}, new ExportedOreVeinInfo.WeightedBlock[] {
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:blackstone_blue_topaz_ore", 35, 35),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:blackstone_topaz_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:blackstone_chalcocite_ore", 25, 25),
                    new ExportedOreVeinInfo.WeightedBlock("gtceu:blackstone_bornite_ore", 15, 15)
            }),
    };
}