name: Deploy mod

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Get the version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

      - name: release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: lNttW2Xl
          modrinth-featured: true
          modrinth-unfeature-mode: subset
          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}

          curseforge-id: 513402
          curseforge-token: ${{ secrets.CF_API_TOKEN }}

          files: |
            build/libs/!(*-@(dev|sources|javadoc)).jar
            build/libs/*-@(dev|sources|javadoc).jar

          name: TerraFirmaGreg-1.20.1-${{ steps.get_version.outputs.version }}
          version: 1.20.1-${{ steps.get_version.outputs.version }}
          version-type: release

          loaders: |
            forge
          game-versions: |
            ${{ github.ref_name }}
          game-version-filter: none
          java: |
            17
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail
